services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - overchain-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - overchain-network
  
  gabrielgcs:
    image: gabrielgcs/dockerhub:questao1
    ports:
      - 3030:3030
      - 50000:50000
      
networks:
  overchain-network:
    driver: bridge
