name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd overchain-web-api
            git pull
            npm install
            npm run build
            pm2 reload dist/src/main.js
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
